# Generated by Django 2.2.20 on 2021-07-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customtext_homepage_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
